
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-18T12:57:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "45ef7c661c3b06bff83a20aa361e50488dc94e09",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
